### ISSUE TITLE
Clarification on Map-Free dataset training.

### ISSUE THREAD

**Issue by JayKarhade** [naver/mast3r#3]
Hi, 

The paper mentions you also trained Mast3r using the mapfree localization dataset - did you use the provided DPT metric depths for training (that you also use for ablations in table 1)? Or did you train the model using the sparse SFM depth from COLMAP reconstructions?

**Comment by vincent-leroy** [comment]
Hi!
It is better to leverage dense annotations, so we ran colmap MVS on all sub-sequences to obtain dense supervision. Note that we also had great results with sparse SfM keypoints, but it is sub-optimal in the end.

Best,
Vincent
