### ISSUE TITLE
How can I get metric depth?

### ISSUE THREAD

**Issue by puyiwen** [naver/mast3r#33]
Hi, I want to get metric depth from mast3r, I use `get_depthmap() `to get it, howerver, I find the size of depthmap is not true. For example, the output size is (512,384), but the depthmap size is (3172,). Can you help me? Thank you very much!

**Comment by ojh6404** [comment]
I was able to get depthmap from this line. mast3r needs (512, 288) images to feed into model, so the depthmap was like (512X288,) and you can reshape this as (512, 288).
https://github.com/naver/mast3r/blob/9e25e47f0fb8f19b3fe66393e8a8faf1233a53d0/mast3r/cloud_opt/sparse_ga.py#L93
