### ISSUE TITLE
map-free benchmark tests

### ISSUE THREAD

**Issue by weitong8591** [naver/mast3r#4]
Hi! Thanks for releasing the code. 

Are you going to release the correspondences and depths(auto) from Mast3R on map-free dataset? Or I can just save the valid matches with their depth using [MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric](https://download.europe.naverlabs.com/ComputerVision/MASt3R/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth)?

Best, 
Tong

**Comment by jerome-revaud** [comment]
Hi. The model checkpoint we are releasing right now is not exactly the same than the one we used for the leaderboard.
However, what you propose to do (saving matches and their depth) should yield similar results.

**Comment by ZiYang-xie** [comment]
> Hi. The model checkpoint we are releasing right now is not exactly the same than the one we used for the leaderboard. However, what you propose to do (saving matches and their depth) should yield similar results.

Thanks for the great work. When do you prepare to release the best checkpoint?

**Comment by jerome-revaud** [comment]
We can't, for legal reasons (some datasets prohibit the redistribution of checkpoints trained on them)

**Comment by weitong8591** [comment]
Thanks! I will use the published checkpoint then.
