### ISSUE TITLE
Hardware and Training time

### ISSUE THREAD

**Issue by wq1999** [naver/mast3r#42]
Hello!First of all, thank you for the great work!!
I would like to know the hardware resources and training time required to train this model.

**Comment by yocabon** [comment]
Hi, we used a machine with 8*A100 gpus; training (finetuning started from the dust3r checkpoint) lasted about 11 days.

**Comment by wq1999** [comment]
> Hi, we used a machine with 8*A100 gpus; training (finetuning started from the dust3r checkpoint) lasted about 11 days.


Ok. Thanks for your reply!

**Comment by wq1999** [comment]
done!
