### ISSUE TITLE
About train details

### ISSUE THREAD

**Issue by nfyfamr** [naver/mast3r#46]
Dear authors, thanks for sharing this great work. I have a quick question. I understand mast3r is trained from pretrained weight of dust3r, for 35 epochs. Then, what gpu and how many of it did you use, and how long time it took? TIA!

**Comment by yocabon** [comment]
the released checkpoint is trained with 50 epochs; see here for your question https://github.com/naver/mast3r/issues/42#issuecomment-2363320826
