### ISSUE TITLE
Error in scene graph pair creation

### ISSUE THREAD

**Issue by vmanzin** [naver/mast3r#55]
The MASt3R-SfM paper describes the algorithm for scene graph construction and has the following snippet:
> All remaining images are then connected to their closest keyframe

However, the code for graph construction uses argmax() on the distance matrix which returns the most distant keyframe:
https://github.com/naver/mast3r/blob/1159b914ccccd80c67af7177808936d5488c6548/mast3r/retrieval/graph.py#L61

It's interesting that the output results are still very good even with this way of creating the scene graph, at least on my specific sample of ~80 scenes. Great work!

**Comment by yocabon** [comment]
Hi, thank you a lot for noticing this error! 
It was introduced when we rewrote retrieval/graph from our internal repository to this one.
