### ISSUE TITLE
Question about ARKit Dataset

### ISSUE THREAD

**Issue by VladimirYugay** [naver/mast3r#59]
Thanks for your amazing work. 

How did you compute the pairs for the ARKit dataset? 

There are more `vga_wide` images than poses, so how did you associate them?

**Comment by yocabon** [comment]
We didn't release the pairing strategy so I'm not going to detail it here (you can read https://github.com/naver/dust3r/issues/146). It involves finding the overlap between the possible pairs of images and selecting some of them.

For the poses, it is written in there: https://github.com/naver/dust3r/blob/main/datasets_preprocess/preprocess_arkitscenes.py#L273
