### ISSUE TITLE
Missing Contribution.md file

### ISSUE THREAD

**Issue by Parth4git** [naver/mast3r#72]
There a need to add a contribution.md file .So, that anyone who want to contribute have a idea of what steps to follow for contribution.

I want to work on this issue. Please assign me this task.

**Comment by Parth4git** [comment]
@yocabon Can I work on this issue

**Comment by Parth4git** [comment]
@yocabon kindly reply to my issue

**Comment by yocabon** [comment]
Hi, getting external contributions is not something we're chasing. We do not have enough resources to properly check them, and maintaining them is out of the question for now.
