### ISSUE TITLE
fast_reciprocal_NNs is extremely slow

### ISSUE THREAD

**Issue by hit2sjtu** [naver/mast3r#91]
I am playing with the visloc demo (InLoc) and find out it is extremely slow.

After some digging, I find the bottleneck is with the fast_reciprocal_NNs used. For example, running the inference for single query-db pair takes only 61ms while fast_reciprocal_NNs takes 950ms on RTX4090. 

As a result, using top-20 candidate database image to match, single localization takes >20 seconds, which is impractical.

Do you have any suggestions or fix?

**Comment by skill-diver** [comment]
Hi, I am wondering have you solved fastnn Inference slow question? If you have, how did you do that?
